#!/usr/bin/env python3
"""
yaml_to_md.py

Generate a Markdown resume from the SAME data.yaml used by resume.typ.

Section order (matches resume.typ):
  summary
  experience (internships merged in)
  education
  skills & interests
  projects
  achievements
  leadership
  activities
  certifications
  stats
  socials

Also lints for keyword repetition: a tool should be named once, in its role's
`stack:`, not restated across bullets.

Usage:
  python3 yaml_to_md.py data.yaml README.md

Dependency:
  pip install pyyaml
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import quote, urlparse

import yaml

# data.yaml is pure data: no markup to translate. Emphasis comes from its
# `emphasize` list, applied here so the PDF and this README agree.

# Keywords shorter than this are too collision-prone to lint (AI, ML, DL, uv).
MIN_LINT_LEN = 5


def links_by_label(links: list[dict]) -> dict[str, str]:
    by_label = {}
    for it in links or []:
        label = str(it.get("label", "")).strip().lower()
        url = str(it.get("url", "")).strip()
        if label and url:
            by_label[label] = url
    return by_label


def url_username(url: str) -> str:
    """Last non-empty path segment, e.g. https://leetcode.com/u/ashu/ -> ashu."""
    parts = [p for p in urlparse(str(url or "")).path.split("/") if p]
    return parts[-1] if parts else ""


# Transparent background, monochrome ink: black in light mode, white in dark.
LIGHT_INK = "bg_color=00000000&title_color=000000&text_color=000000&icon_color=000000"
DARK_INK = "bg_color=00000000&title_color=ffffff&text_color=ffffff&icon_color=ffffff"


def themed(alt: str, light: str, dark: str, href: str) -> str:
    """
    A <picture> that follows the reader's system theme. Plain Markdown cannot
    do this, but kramdown passes raw HTML through and prefers-color-scheme is
    handled by the browser, so it works on GitHub Pages and on github.com.
    """
    return (
        f'<a href="{href}">'
        f"<picture>"
        f'<source media="(prefers-color-scheme: dark)" srcset="{dark}">'
        f'<img alt="{alt}" src="{light}">'
        f"</picture></a>"
    )


def build_stats_cards(links: list[dict], repo: str = "") -> list[str]:
    """
    Profile stat cards, one per returned block so each renders on its own line.
    Ordered by what a visitor looks at first: the contribution snake, then
    activity, then languages, then competitive programming.

    github-readme-stats.vercel.app is deliberately not used: it answers 503.
    github-stats-extended.vercel.app is the drop-in replacement and serves a
    real card. streak-stats.demolab.com is skipped as well - it answered 200
    on one check and was unreachable on another, and a card that is down
    renders as a broken image on the live site.
    """
    by_label = links_by_label(links)
    cards = []

    github = by_label.get("github")

    # Contribution snake, generated by .github/workflows/snake.yml in this
    # repository and published to its `output` branch in a light and a dark
    # variant.
    if repo:
        snake = f"https://raw.githubusercontent.com/{repo}/output/github-contribution-grid-snake"
        cards.append(
            themed(
                "Contribution snake",
                f"{snake}.svg",
                f"{snake}-dark.svg",
                f"https://github.com/{repo}",
            )
        )

    if github:
        user = url_username(github)
        api = "https://github-stats-extended.vercel.app/api"
        for alt, path, extra in (
            ("GitHub Stats", "", "show_icons=true&hide_border=true"),
            (
                "Top Languages",
                "/top-langs",
                "layout=compact&hide_border=true&langs_count=10",
            ),
        ):
            stem = f"{api}{path}?username={user}&{extra}"
            cards.append(
                themed(alt, f"{stem}&{LIGHT_INK}", f"{stem}&{DARK_INK}", github)
            )

        # Trophies. The widely used github-profile-trophy.vercel.app answers
        # 402 (Vercel quota exceeded); this mirror serves the same cards.
        trophy = f"https://github-trophies.vercel.app/?username={user}&no-frame=true&column=4&margin-w=6&theme="
        cards.append(
            themed("GitHub Trophies", f"{trophy}flat", f"{trophy}darkhub", github)
        )

    leetcode = by_label.get("leetcode")
    if leetcode:
        # Explicit per-theme URLs rather than leetcard's self-switching card.
        # The default embeds its own prefers-color-scheme rules, which a
        # browser honours but GitHub's image pipeline does not - that is why
        # the card was right on the site yet stayed dark in every README.
        # <picture> is the mechanism GitHub documents, and works in both.
        card = f"https://leetcard.jacoblin.cool/{url_username(leetcode)}?ext=heatmap&theme="
        cards.append(themed("LeetCode Stats", f"{card}light", f"{card}dark", leetcode))

    return cards


def build_quote() -> str:
    """Random developer quote, following the reader's system colour scheme."""
    q = "https://quotes-github-readme.vercel.app/api?type=horizontal&theme="
    return (
        "<picture>"
        f'<source media="(prefers-color-scheme: dark)" srcset="{q}dark">'
        f'<img alt="Random dev quote" src="{q}light">'
        "</picture>"
    )


def stress(s: str, phrases: list[str]) -> str:
    """Bold each `emphasize` phrase wherever it occurs."""
    for ph in phrases or []:
        if ph in s:
            s = s.replace(ph, f"**{ph}**")
    return s


def entry_line(e: dict) -> str:
    """Render the shared name / url / detail / links shape."""
    head = md_link(e["name"], e["url"]) if e.get("url") else e["name"]
    line = f"**{head}**"
    if e.get("detail"):
        line += f": {e['detail']}"
    if e.get("links"):
        ls = ", ".join(md_link(l["name"], l["url"]) for l in e["links"])
        line += f". {e.get('links_label', 'Links')}: {ls}"
    return line


def md_link(text: str, url: str) -> str:
    text = str(text or "").strip()
    url = str(url or "").strip()
    return f"[{text}]({url})" if text and url else (text or url)


def join_comma(items) -> str:
    items = [str(x).strip() for x in (items or []) if str(x).strip()]
    return ", ".join(items)


def section(md: list[str], title: str) -> None:
    md.append(f"## {title}")
    md.append("")


def lint_repetition(data: dict) -> list[str]:
    """
    A tool belongs in exactly one place: its role's `stack:`. Report keywords
    restated across bullets, and stack entries missing from the skills
    inventory (which means the SKILLS section has drifted).
    """
    warnings: list[str] = []

    inventory = {
        str(i).strip()
        for cat in data.get("skills", []) or []
        for i in (cat.get("items", []) or [])
        if str(i).strip()
    }

    bullets: list[str] = []
    for job in data.get("experience", []) or []:
        bullets.extend(str(b) for b in (job.get("bullets", []) or []))
    for key in ("leadership", "activities"):
        bullets.extend(str(b) for b in (data.get(key, []) or []))

    stack_terms = {
        str(s).strip()
        for job in data.get("experience", []) or []
        for s in (job.get("stack", []) or [])
        if str(s).strip()
    }

    for term in sorted(stack_terms | inventory):
        if len(term) < MIN_LINT_LEN:
            continue
        pattern = re.compile(rf"(?<![\w/]){re.escape(term)}(?![\w/])", re.IGNORECASE)
        hits = sum(1 for b in bullets if pattern.search(b))
        if hits > 1:
            warnings.append(f"  repeated across {hits} bullets: {term!r}")

    for term in sorted(stack_terms - inventory):
        warnings.append(
            f"  in a role stack but missing from skills inventory: {term!r}"
        )

    return warnings


def main() -> int:
    in_path = Path(sys.argv[1] if len(sys.argv) > 1 else "data.yaml")
    out_path = Path(sys.argv[2] if len(sys.argv) > 2 else "README.md")

    data = yaml.safe_load(in_path.read_text(encoding="utf-8"))
    basics = data.get("basics", {}) or {}
    emphasize = data.get("emphasize", []) or []

    # Header (keeps same variables as resume)
    name = str(basics.get("name", "")).strip() or "Resume"
    profile = str(basics.get("headline", "")).strip() or "Resume"
    _titles = str(basics.get("titles", "")).strip()
    email = str(basics.get("email", "")).strip()
    location = str(basics.get("location", "")).strip()
    work_auth = str(basics.get("work_authorization", "")).strip()
    resume_pdf = str(basics.get("resume_pdf", "")).strip()
    links = basics.get("links", []) or []

    # No name heading here. GitHub Pages renders this file inside a theme whose
    # sidebar already prints `title` from _config.yml, so an H1 with the name
    # showed it twice. The sidebar carries the name; the page opens on the role.
    # (`name` is still used for the footer credit below.)
    md: list[str] = []

    # `titles` is ATS title-matching padding for the PDF; next to the headline
    # it just repeats "Data Scientist", so the site shows the headline only.
    if profile:
        md.append(f"# {profile}")
        md.append("")

    where = [b for b in (location, work_auth) if b]
    if where:
        md.append(" · ".join(where))
        md.append("")

    # Short labels here, unlike the PDF. The website is read by humans; only
    # the PDF needs the URL spelled out for ATS text extraction, and eight full
    # URLs on one line render as an unreadable wall.
    header_bits = []
    if email:
        header_bits.append(md_link(email, f"mailto:{email}"))
    for l in links:
        url = str(l.get("url", "")).strip()
        shown = str(l.get("label", "") or l.get("display", "")).strip()
        if shown and url:
            header_bits.append(md_link(shown, url))
    if header_bits:
        md.append(" · ".join(header_bits))
        md.append("")

    if resume_pdf:
        md.append(f"📄 **[Download Resume (PDF)]({quote(resume_pdf)})**")
        md.append("")

    # 1) summary
    summary = str(data.get("summary", "") or "").strip()
    if summary:
        section(md, "🎯 SUMMARY")
        md.append(summary)
        md.append("")

    # 2) experience (internships merged in)
    section(md, "💼 EXPERIENCE")
    for job in data.get("experience", []) or []:
        role = str(job.get("role", "")).strip()
        role_url = str(job.get("role_url", "") or "").strip()
        dates = str(job.get("dates", "")).strip()
        company = str(job.get("company", "")).strip()
        loc = str(job.get("location", "")).strip()

        role_display = md_link(role, role_url) if role_url else role
        # Never use "|" as a separator: kramdown (GitHub Pages' Markdown
        # engine) parses any line containing pipes as a table, which turned
        # every job entry into a bordered 2-column table on the site.
        md.append(f"**{company}** · _{loc}_<br>")
        md.append(f"_{role_display}_ · _({dates})_")

        stack = join_comma(job.get("stack", []) or [])
        if stack:
            md.append("")
            md.append(f"**Stack:** {stack}")
        md.append("")

        for b in job.get("bullets", []) or []:
            md.append(f"- {stress(b, emphasize)}")
        md.append("")

    # 3) education
    section(md, "🎓 EDUCATION")
    for e in data.get("education", []) or []:
        md.append(
            f"**{e['degree']}** _from_ {e['institution']} — {e['dates']}<br>"
        )
    md.append("")

    # 4) skills
    section(md, "🛠️ SKILLS & INTERESTS")
    for s in data.get("skills", []) or []:
        cat = str(s.get("category", "")).strip()
        items = join_comma(s.get("items", []) or [])
        if cat and items:
            md.append(f"- **{cat}:** {items}")
        elif cat:
            md.append(f"- **{cat}:**")
    md.append("")

    # 5) projects  |  6) achievements  - same name/url/detail/links shape
    section(md, "📂 PROJECTS")
    for p in data.get("projects", []) or []:
        md.append(f"- {entry_line(p)}")
    md.append("")

    section(md, "🏆 ACHIEVEMENTS")
    for a in data.get("achievements", []) or []:
        md.append(f"- {entry_line(a)}")
    md.append("")

    # 7) leadership  |  activities - plain statements
    section(md, "🤝 LEADERSHIP")
    for x in data.get("leadership", []) or []:
        md.append(f"- {x}")
    md.append("")

    section(md, "🎨 ACTIVITIES")
    for x in data.get("activities", []) or []:
        md.append(f"- {x}")
    md.append("")

    # 8) certifications
    section(md, "📜 CERTIFICATIONS")
    for c in data.get("certifications", []) or []:
        md.append(f"- {entry_line(c)}")
    md.append("")

    stats = build_stats_cards(links, str(basics.get("repo", "") or "").strip())
    if stats:
        section(md, "📈 STATS")
        # Blank line between each: consecutive lines would collapse into one
        # paragraph and the cards would sit side by side.
        for card in stats:
            md.append(card)
            md.append("")

    section(md, "✍️ RANDOM DEV QUOTE")
    md.append(build_quote())
    md.append("")

    # No SOCIALS section: the profile links live in the header at the top of
    # the page, and repeating them as badges at the bottom was the same set of
    # destinations twice.
    md.append("---")
    md.append("")

    github_url = links_by_label(links).get("github", "")

    if github_url:
        md.append(f"Made with ❤️ by [{name}]({github_url})")
    else:
        md.append(f"Made with ❤️ by {name}")

    out_path.write_text("\n".join(md).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {out_path} from {in_path}")

    warnings = lint_repetition(data)
    if warnings:
        print(f"\nkeyword repetition ({len(warnings)}):")
        print("\n".join(warnings))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
